second attempt

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -91,7 +91,7 @@ jobs:
     - name: Run Collatz problem
       run: |
         echo "Running Collatz problem solution..."
-        dotnet fsi --exec collatz.fsx || (echo "::error::collatz.fsx failed to execute" && exit 1)
+        dotnet fsi --exec "3n+1.fsx" || (echo "::error::\"3n+1.fsx\" failed to execute" && exit 1)
     
     - name: Run unit tests
       run: |
